basePath: /
definitions:
  dto.ProductRequest:
    properties:
      description:
        type: string
      id:
        type: integer
      images:
        type: string
      name:
        type: string
      rating:
        type: number
      stock:
        type: integer
    type: object
  dto.ProductResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      images:
        type: string
      name:
        type: string
      rating:
        type: number
      stock:
        type: integer
    type: object
  dto.ResponseProduct:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.ProductResponse'
        type: array
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.UpdateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.UserResponse:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: API documentation
  title: Koda API
  version: "1.0"
paths:
  /products:
    get:
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create new product
      parameters:
      - description: Create product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dto.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
      summary: Create a product
      tags:
      - Products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product
      parameters:
      - description: Delete product
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
      summary: Delete a product
      tags:
      - Products
    get:
      description: Get Product By Id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
      summary: Get Product By Id
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Update product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dto.ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseProduct'
      summary: Edit Product By Id
      tags:
      - Products
  /users:
    get:
      description: Get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      summary: Get users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      summary: Create a user
      tags:
      - Users
  /users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: Delete User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      summary: Delete user By Id
      tags:
      - Users
    get:
      description: Get users
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      summary: Get users
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: Update user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      summary: Update user By Id
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: 'Type "Bearer" followed by a space and JWT token. Example: "Bearer
      eyJhbGciO..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
